services:
  app:
    container_name: TOC-web_scraping
    build:
      context: ./
      dockerfile: Dockerfile
    # ports:
    #   - '5000:5000'
    networks:
      - tunnel

networks:
  tunnel:
    external: true