services:
  app:
    container_name: TOC-web_scraping
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
      - tunnel
    # environment:
    #   - PYTHONUNBUFFERED=0

networks:
  tunnel:
    external: true