name: toc-web-scraping

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: pwd && docker build . --file Dockerfile --tag flask-python-toc:V2
